### ISSUE TITLE
todo el codigo mal

### ISSUE THREAD

**Issue by angelcastineira** [NicolasRodriguezSteuerberg/JugandoCOnPullRequest#1]
@NicolasRodriguezSteuerberg que mal

**Comment by angelcastineira** [comment]
> @NicolasRodriguezSteuerberg que mal

tienes que añadir un sout("gabriel trabaja")

**Comment by NicolasRodriguezSteuerberg** [comment]
Mmmm me parece bien añadir otro sout, pero no que saque ese mensaje, dame mas opciones

**Comment by angelcastineira** [comment]
sout("**putita**") me parece lo mas apropiado

**Comment by NicolasRodriguezSteuerberg** [comment]
Mmm okey puede servir eso, encargate de hacer un pull request añadiendo eso y cierra el issue

**Comment by angelcastineira** [comment]
soluciionado
